
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import backend

import tkinter as tk
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.pyplot as plt

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\pythonapp\v2\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def current_graphs():
    t = [i for i in range(0, 500 * 56, 500)]
    current = backend.get_current()
    print(current)
    print(t)
    top = tk.Toplevel(window)
    top.title("Grafice curent - Robot Industrial")

    grafice_frame = tk.Frame(top)
    grafice_frame.pack(padx=10, pady=10)

    for i in range(4):
        frame = tk.Frame(grafice_frame)
        frame.grid(row=i // 2, column=i % 2, padx=5, pady=5)

        fig, ax = plt.subplots(figsize=(4, 2))
        ax.plot(t, current[i])
        ax.set_title(f"Articulatia {i+1}")
        ax.set_xlabel("Timp (s)")
        ax.set_ylabel("Curent (A)")
        fig.tight_layout()

        canvas2 = FigureCanvasTkAgg(fig, master=frame)
        canvas2.draw()
        canvas2.get_tk_widget().pack()


def choose_space(btn):
    if btn["text"] == "-":
        return

    fereastra_noua = tk.Toplevel(window)
    fereastra_noua.geometry("500x129")
    fereastra_noua.configure(bg="#FFFFFF")

    canvas2 = Canvas(
        fereastra_noua,
        bg="#FFFFFF",
        height=129,
        width=500,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas2.place(x=0, y=0)
    canvas2.create_text(
        9.0,
        9.0,
        anchor="nw",
        text="Cum doriți să vă deplasați la următorul punct?",
        fill="#0717CD",
        font=("Comic Sans MS", 23 * -1)
    )

    button_image_c = PhotoImage(file=relative_to_assets("button_c.png"))
    button_c = Button(
        fereastra_noua,
        image=button_image_c,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: [backend.move_cart(btn, [poz1, poz2, poz3, poz4, poz5], canvas, posX, posY, posZ),
                         fereastra_noua.destroy()],
        relief="flat"
    )
    button_c.image = button_image_c  # păstrăm referința
    button_c.place(x=11.0, y=75.0, width=200.0, height=40.0)

    button_image_a = PhotoImage(file=relative_to_assets("button_a.png"))
    button_a = Button(
        fereastra_noua,
        image=button_image_a,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: [backend.update_pos(btn, [poz1, poz2, poz3, poz4, poz5], canvas, posX, posY, posZ),
                         fereastra_noua.destroy()],
        relief="flat"
    )
    button_a.image = button_image_a
    button_a.place(x=285.0, y=75.0, width=200.0, height=40.0)

    fereastra_noua.resizable(False, False)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    400.0,
    0.0,
    800.0,
    600.0,
    fill="#0617CC",
    outline="")

canvas.create_text(
    415.0,
    0.0,
    anchor="nw",
    text="Sistem de conducere Scorbot-ER VII ",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1, "bold")
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    200.0,
    404.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    102.0,
    309.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    37.0,
    390.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    269.0,
    539.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    220.0,
    390.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    87.0,
    420.0,
    image=image_image_6
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.plus_value("Motor 3", step, poz3, canvas, posX, posY, posZ),
    relief="flat"
)
button_1.place(
    x=135.0,
    y=113.0,
    width=30.0,
    height=30.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.minus_value("Motor 3", step, poz3, canvas, posX, posY, posZ),
    relief="flat"
)
button_2.place(
    x=22.0,
    y=112.0,
    width=30.0,
    height=30.0
)

poz3 = canvas.create_text(
    85.0,
    113.0,
    anchor="nw",
    text="0",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    37.0,
    82.0,
    anchor="nw",
    text="Articulația 3",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.plus_value("Motor 2", step, poz2, canvas, posX, posY, posZ, 1),
    relief="flat"
)
button_3.place(
    x=363.0,
    y=48.0,
    width=30.0,
    height=30.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.minus_value("Motor 2", step, poz2, canvas, posX, posY, posZ, 1),
    relief="flat"
)
button_4.place(
    x=250.0,
    y=47.0,
    width=30.0,
    height=30.0
)

poz2 = canvas.create_text(
    310.0,
    48.0,
    anchor="nw",
    text="0",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    265.0,
    17.0,
    anchor="nw",
    text="Articulația 2",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.minus_value("Motor 1", step, poz1, canvas, posX, posY, posZ),
    relief="flat"
)
button_6.place(
    x=23.0,
    y=47.0,
    width=30.0,
    height=30.0
)

poz1 = canvas.create_text(
    85,
    48.0,
    anchor="nw",
    text="0",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    37.0,
    17.0,
    anchor="nw",
    text="Articulația 1",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.plus_value("Motor 4", step, poz4, canvas, posX, posY, posZ, 1),
    relief="flat"
)
button_7.place(
    x=363.0,
    y=113.0,
    width=30.0,
    height=30.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.minus_value("Motor 4", step, poz4, canvas, posX, posY, posZ, 1),
    relief="flat"
)
button_8.place(
    x=250.0,
    y=112.0,
    width=30.0,
    height=30.0
)

poz4 = canvas.create_text(
    310.0,
    113.0,
    anchor="nw",
    text="0",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    265.0,
    82.0,
    anchor="nw",
    text="Articulația 4",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    310.0,
    157.0,
    anchor="nw",
    text="Pas",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    320.0,
    203.0,
    image=entry_image_1
)
step = Entry(
    bd=1,
    bg="#0717CD",
    fg="#f0f1f5",
    highlightthickness=0,
    font=("Comic Sans MS", 14),
    justify="center"
)
step.place(
    x=251.0,
    y=188.0,
    width=138.0,
    height=28.0
)
step.insert(0, "100")

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.plus_value("Motor 5", step, poz5, canvas, posX, posY, posZ),
    relief="flat"
)
button_11.place(
    x=135.0,
    y=188.0,
    width=30.0,
    height=30.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.minus_value("Motor 5", step, poz5, canvas, posX, posY, posZ),
    relief="flat"
)
button_12.place(
    x=22.0,
    y=187.0,
    width=30.0,
    height=30.0
)

poz5 = canvas.create_text(
    85.0,
    188.0,
    anchor="nw",
    text="0",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    37.0,
    157.0,
    anchor="nw",
    text="Articulația 5",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    289.0,
    263.0,
    anchor="nw",
    text="Unealta",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_image_13_2 = PhotoImage(
    file=relative_to_assets("deschide.png"))
button_13 = Button(
    image=button_image_13_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.control_gripper(button_13, button_image_13, button_image_13_2),
    relief="flat"
)
button_13.place(
    x=254.0,
    y=294.0,
    width=139.0,
    height=30.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.save_cfg(canvas, [poz1, poz2, poz3, poz4, poz5], [button_15, button_16, button_17, button_18, button_19]),
    relief="flat"
)
button_14.place(
    x=451.0,
    y=554.0,
    width=300.0,
    height=54.0
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    600.0,
    383.0,
    image=image_image_7
)

canvas.create_text(
    535.0,
    237.0,
    anchor="nw",
    text="Puncte salvate",
    fill="#000000",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    439.0,
    48.0,
    anchor="nw",
    text="Conectare UART:",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    text="-",
    compound="center",  
    font=("Comic Sans MS", 8, "bold"),
    fg="white",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choose_space(button_15),
    relief="flat"
)
button_15.place(
    x=418.0,
    y=282.0,
    width=366.0,
    height=35.0
)

button_16 = Button(
    image=button_image_15,
    text="-",
    compound="center",  
    font=("Comic Sans MS", 8, "bold"),
    fg="white",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choose_space(button_16),
    relief="flat"
)
button_16.place(
    x=418.0,
    y=328.0,
    width=366.0,
    height=35.0
)

button_17 = Button(
    image=button_image_15,
    text="-",
    compound="center",  
    font=("Comic Sans MS", 8, "bold"),
    fg="white",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choose_space(button_17),
    relief="flat"
)
button_17.place(
    x=418.0,
    y=375.0,
    width=366.0,
    height=35.0
)

button_18 = Button(
    image=button_image_15,
    text="-",
    compound="center",  
    font=("Comic Sans MS", 8, "bold"),
    fg="white",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choose_space(button_18),
    relief="flat"
)
button_18.place(
    x=418.0,
    y=420.0,
    width=366.0,
    height=35.0
)

button_19 = Button(
    image=button_image_15,
    text="-",
    compound="center",  
    font=("Comic Sans MS", 8, "bold"),
    fg="white",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choose_space(button_19),
    relief="flat"
)
button_19.place(
    x=417.0,
    y=466.0,
    width=366.0,
    height=35.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: backend.plus_value("Motor 1", step, poz1, canvas, posX, posY, posZ),
    relief="flat"
)
button_5.place(
    x=136.0,
    y=48.0,
    width=30.0,
    height=30.0
)

canvas.create_text(
    439.0,
    132.0,
    anchor="nw",
    text="Poziție curentă",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

canvas.create_text(
    612.0,
    90.0,
    anchor="nw",
    text="X:",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

button_image_20 = PhotoImage(
    file=relative_to_assets("button_20.png"))
button_20 = Button(
    image=button_image_20,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_20 clicked"),
    relief="flat"
)
button_20.place(
    x=648.0,
    y=87.0,
    width=30.0,
    height=30.0
)

button_image_21 = PhotoImage(
    file=relative_to_assets("button_21.png"))
button_21 = Button(
    image=button_image_21,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_21 clicked"),
    relief="flat"
)
button_21.place(
    x=761.0,
    y=88.0,
    width=30.0,
    height=30.0
)

canvas.create_text(
    612.0,
    132.0,
    anchor="nw",
    text="Y:",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

button_image_22 = PhotoImage(
    file=relative_to_assets("button_20.png"))
button_22 = Button(
    image=button_image_20,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_22 clicked"),
    relief="flat"
)
button_22.place(
    x=648.0,
    y=129.0,
    width=30.0,
    height=30.0
)

button_image_23 = PhotoImage(
    file=relative_to_assets("button_21.png"))
button_23 = Button(
    image=button_image_23,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_23 clicked"),
    relief="flat"
)
button_23.place(
    x=761.0,
    y=130.0,
    width=30.0,
    height=30.0
)

canvas.create_text(
    612.0,
    173.0,
    anchor="nw",
    text="Z:",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

button_image_24 = PhotoImage(
    file=relative_to_assets("button_20.png"))
button_24 = Button(
    image=button_image_24,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_24 clicked"),
    relief="flat"
)
button_24.place(
    x=648.0,
    y=171.0,
    width=30.0,
    height=30.0
)

button_image_25 = PhotoImage(
    file=relative_to_assets("button_21.png"))
button_25 = Button(
    image=button_image_25,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_25 clicked"),
    relief="flat"
)
button_25.place(
    x=761.0,
    y=172.0,
    width=30.0,
    height=30.0
)

posX = canvas.create_text(
    698.0,
    88.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

posY = canvas.create_text(
    698.0,
    129.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

posZ = canvas.create_text(
    698.0,
    173.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Comic Sans MS", 20 * -1)
)

button_image_26 = PhotoImage(
    file=relative_to_assets("button_26.png"))
button_26 = Button(
    image=button_image_26,
    borderwidth=0,
    highlightthickness=0,
    command=current_graphs,
    relief="flat"
)
button_26.place(
    x=484.0,
    y=159.0,
    width=61.0,
    height=61.0
)

port_frame = tk.Frame(window)
port_frame.pack(pady=5)
port_var = tk.StringVar(value="Port")
ports = backend.get_available_ports()
port_menu = tk.OptionMenu(port_frame, port_var, *ports)
port_menu.pack(side=tk.LEFT)
connect_button = tk.Button(port_frame, text="Conectează", command=lambda: backend.connect_arduino(port_var, connect_button))
connect_button.pack(side=tk.LEFT)

port_frame.place(
    x=620.0,
    y=48.0
)

window.resizable(False, False)
